Add anti-bribery and events policies
github/site-policy pull request #121
Opened 2018-08-08 20:30 UTC by vollmera

2018-08-08 20:34 UTC, mlinksva approved these changes
Exact copy of additional policies now published at https://help.github.com/categories/site-policy/

2018-08-08 20:36 UTC, merged

2018-08-08 21:29 UTC, KOLANICH commented
I wonder if this a result of MS acquisition or they have been existing long before, but were just not published.

2020-06-06 21:00 UTC, insanm61 commented
Ok

2021-03-20 08:02 UTC, luismedicina23 commented on Policies/github-anti-bribery-statement.md
> +title: GitHub Anti-Bribery Statement
@Autor

2021-04-16 17:43 UTC, Budda0ne reviewed
Рев


```

2021-08-10 22:55 UTC, d066 commented
thanks

2021-08-11 13:24 UTC, codedfile commented
https://github.com/Hacker0x01/docs.hackerone.com/commit/b3c0e0f01c6d45066be08635c83d09aca033487c#commitcomment-54728323

2021-09-28 17:44 UTC, Hecim1984 reviewed
🎉🚀

2021-10-13 06:09 UTC, 966563058015 commented
![image](https://user-images.githubusercontent.com/6750723/137076626-9d786dc9-ca7c-4fe7-9435-454b5a0c799b.jpeg)

2021-11-02 01:44 UTC, NikkieDickie reviewed
> 
411

2021-11-14 16:22 UTC, Jelisacooper4 reviewed
#DoubleGrowthLLC

2021-12-20 06:24 UTC, Abdullah9aleh reviewed
Q

2022-01-15 15:06 UTC, Neo-wise approved these changes

2022-03-03 01:18 UTC, ALLARDLEE commented
Support

2022-03-03 01:19 UTC, ALLARDLEE commented
Support

2022-03-05 14:20 UTC, urHeQWjQ2D6GGLz commented
>

2022-03-05 14:21 UTC, urHeQWjQ2D6GGLz commented
- [ ] >

2022-05-28 04:36 UTC, Neo-wise approved these changes

2022-11-28 22:51 UTC, Systemcyruss88 approved these changes
Policies/github-anti-bribery-statement.md/cryptoversion

2022-12-16 21:29 UTC, Bezzo100-lab approved these changes

2022-12-16 21:29 UTC, Bezzo100-lab commented on Policies/github-event-terms.md
> +title: GitHub Event Terms
Amanda Brandenburgh

2023-06-03 18:31 UTC, ziggy74ai commented
What does this mean

2023-06-25 00:48 UTC, Neowise01 commented on Policies/github-gifts-and-entertainment-policy.md
> +title: GitHub Gifts and Entertainment Policy
> Policies/github-event-terms.md

2023-06-26 03:26 UTC, ziggy74ai approved these changes
> > > > Kt09Sakhal899`~~~~`

2023-06-26 03:26 UTC, ziggy74ai commented on Policies/github-event-code-of-conduct.md
> +Portions of this Code of Conduct are based on the [example anti-harassment policy](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy) from the Geek Feminism wiki, created by the Ad
🙃[]()<!-- Error while uploading .trashed-1687700238-VSCode-win32-x64-1.78.2.zip -->
WZ00️⃣😔😔🎊0️⃣0️⃣

2023-06-26 03:26 UTC, ziggy74ai commented on Policies/github-anti-bribery-statement.md
> +GitHub upholds our commitment to ethical business practices, including by prohibiting bribery and corruption. As [Transparency International](https://www.transparency.org/what-is-corruption#costs-of-
https://t.me/+lllloex44848dd9r440

2023-06-28 01:27 UTC, Chixonya22 commented on Policies/github-gifts-and-entertainment-policy.md
> +title: GitHub Gifts and Entertainment Policy
Bit

2024-01-18 23:37 UTC, Hwycjcd commented
https://youtube.com/@user-sy3pu6ed5o?si=_MYP_dEqM1isZBj3

2024-01-18 23:37 UTC, Hwycjcd commented on Policies/github-gifts-and-entertainment-policy.md
> +title: GitHub Gifts and Entertainment Policy
https://github.com/github/site-policy/pull/121#pullrequestreview-1488135158

2024-01-29 19:28 UTC, 14126120941512121180414934817 commented
16181510091614416110318151840966101510185514415611181261518

2024-01-29 20:01 UTC, 14126120941512121180414934817 commented
****

2024-04-17 13:41 UTC, Dramaga11 approved these changes

2024-06-04 22:53 UTC, An010299 commented
A educação está evoluindo e com isso o desenvolvimento também.  Aquele que sabe estará  liberto e com maior potencial e inspiração!

2024-06-04 22:56 UTC, An010299 commented on Policies/github-anti-bribery-statement.md
> +GitHub upholds our commitment to ethical business practices, including by prohibiting bribery and corruption. As [Transparency International](https://www.transparency.org/what-is-corruption#costs-of-
Auditandobe andando criaremos novas canções.

2024-07-03 00:33 UTC, An010299 requested changes

2024-08-02 04:16 UTC, Green369-1 approved these changes

2024-08-02 04:17 UTC, Green369-1 approved these changes

2024-08-22 06:37 UTC, Lobotwallker commented on Policies/github-event-code-of-conduct.md
> +---
Como instalar

2024-09-02 22:14 UTC, Dixie5644 approved these changes
300

2024-09-17 12:35 UTC, nelegalrap reviewed
https://github.com/melegalofficial?tab=stars

2024-10-29 16:32 UTC, leroy182 commented
>

2024-10-29 16:32 UTC, leroy182 reviewed
@leroy182

2024-10-29 16:41 UTC, leroy182 commented on Policies/github-anti-bribery-statement.md
> +GitHub upholds our commitment to ethical business practices, including by prohibiting bribery and corruption. As [Transparency International](https://www.transparency.org/what-is-corruption#costs-of-
@leroy182 to ethical business practices. Including as transparency International. 
https://www.transparency.org/@leroy182

2024-12-17 02:56 UTC, Phamduy1247 reviewed
Lo

2025-01-21 16:52 UTC, Gitrris approved these changes

2025-01-21 16:53 UTC, Gitrris approved these changes

2025-02-09 13:46 UTC, Fiyaas approved these changes

2025-02-09 13:47 UTC, Fiyaas approved these changes

2025-02-16 21:13 UTC, Dustin4444 approved these changes

2025-03-26 18:31 UTC, draghtnight reviewed
body, html {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: Arial, sans-serif;
}

.container {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

h1 {
    text-align: center;
}

form {
    display: flex;
    justify-content: space-between;
}

input {
    flex-grow: 1;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px 0 0 5px;
}

button {
    padding: 10px 20px;
    border: none;
    background-color: #28a745;
    color: white;
    cursor: pointer;
    border-radius: 0 5px 5px 0;
}

button:hover {
    background-color: #218838;
}

ul {
    list-style-type: none;
    padding: 0;
}

li {
    display: flex;
    justify-content: space-between;
    padding: 10px;
    border-bottom: 1px solid #ddd;
}

li:last-child {
    border-bottom: none;
}

li button {
    background-color: #dc3545;
}

li button:hover {
    background-color: #c82333;
}

2025-03-31 18:13 UTC, xupne2-gehcyF-vipdin reviewed
楽しい

2025-07-16 13:43 UTC, autumnthothincorperated commented on Policies/github-event-terms.md
> +title: GitHub Event Terms
The terms and policy are an important gideline.

2025-07-24 20:55 UTC, shinedura commented
"Glass that glows, aluminium that lasts — crafted by ShineDura hands."

2026-01-28 05:20 UTC, otbotb371-lgtm commented
> "Glass that glows, aluminium that lasts — crafted by ShineDura hands."

2026-03-24 04:11 UTC, dameonx69washington-beep approved these changes

2026-03-24 15:17 UTC, autumnthothincorperated reviewed
work-horse-re-write-256

2026-05-09 08:21 UTC, amartinezjr0310310-cyber reviewed
This is amazing 😀

2026-05-25 08:46 UTC, 1sttatech-789 approved these changes

2026-06-02 20:23 UTC, grewaldetective7-tech approved these changes

2026-07-19 18:31 UTC, ghost approved these changes

2026-08-12 16:55 UTC, noorizanbintiabdulmalik85 commented
Picing and aplications from group companies github interprise 2023,TNB METER WIFI BROKEN,AND DATA ![Screenshot_2026-08-08-14-49-18-05_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/de52abf3-70b0-45f0-9232-897e518da54c)

![Screenshot_2026-08-08-14-51-53-80_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/540630a0-a147-44ce-a388-d9edf7cca44f)

![Screenshot_2026-08-08-14-51-26-25_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/6bddc1ad-c795-4c76-ba91-107446e96660)

![Screenshot_2026-08-08-14-52-20-46_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/eff6c9c1-d825-4c61-a7ed-bd9fe860254e)

![Screenshot_2026-08-08-14-53-01-67_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/0384d7c4-dd59-4194-adc5-6d2fc83f75cd)

![Screenshot_2026-08-08-14-52-43-11_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/3fab484b-54dc-4c52-9469-01b7f4faba6c)

![Screenshot_2026-08-08-14-53-25-17_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/89798310-75ef-4054-8633-eb7eceb71f19)

![IMG-20260808-WA0059(1).jpg](https://github.com/user-attachments/assets/c008d524-0617-42c5-93a9-a0f2a0d3a582)

![IMG-20260808-WA0064.jpg](https://github.com/user-attachments/assets/e0ec2cf4-340e-4cee-bc98-986b656f6209)

![IMG-20260808-WA0062.jpg](https://github.com/user-attachments/assets/65cf5cd4-5d82-4094-842f-0e835edad29b)

![Screenshot_2026-08-13-00-47-28-35_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/745741be-8317-4342-b210-aa92582dcd09)

![Screenshot_2026-08-10-22-03-39-49_a23b203fd3aafc6dcb84e438dda678b6.jpg](https://github.com/user-attachments/assets/60d31421-34d7-4a70-a002-960a361fabac)

![FB_IMG_1786370106718.jpg](https://github.com/user-attachments/assets/80cfc256-b669-4b07-88da-7fd384b4a1b2)

![IMG-20260808-WA0060.jpg](https://github.com/user-attachments/assets/416a39cd-5412-4f4b-b876-e10bb849356c)

![IMG-20260808-WA0063.jpg](https://github.com/user-attachments/assets/f111a1d8-349c-4c85-8951-f3bf26f729bf)

2026-10-13 14:38 UTC, moosaharoon789 requested changes
Full request

2026-10-13 14:41 UTC, moosaharoon789 commented
> 

Full request

2026-10-13 14:42 UTC, moosaharoon789 commented
All full request

2026-10-13 14:43 UTC, moosaharoon789 commented
> https://github.com/melegalofficial?tab=stars

Full request

2026-10-13 14:44 UTC, moosaharoon789 commented
> 300

Full request

2026-10-13 14:46 UTC, moosaharoon789 commented
> Lo

Full request